#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversationTracker.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db4dbef5644331495092c7a4930039d3da")]
	public partial class AppHarborDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AppHarborDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db4dbef5644331495092c7a4930039d3daConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AppHarborDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppHarborDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppHarborDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppHarborDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_DeleteConversation")]
		public int prc_DeleteConversation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_RetrieveConversations")]
		public ISingleResult<prc_RetrieveConversationsResult> prc_RetrieveConversations()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<prc_RetrieveConversationsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_InsertConversation")]
		public ISingleResult<prc_InsertConversationResult> prc_InsertConversation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConversationDate", DbType="DateTime")] System.Nullable<System.DateTime> conversationDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Environment", DbType="NVarChar(100)")] string environment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Who", DbType="NVarChar(100)")] string who, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RateOfUnease", DbType="SmallInt")] System.Nullable<short> rateOfUnease, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Notes", DbType="NVarChar(1000)")] string notes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), conversationDate, environment, who, rateOfUnease, notes);
			return ((ISingleResult<prc_InsertConversationResult>)(result.ReturnValue));
		}
	}
	
	public partial class prc_RetrieveConversationsResult
	{
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _ConversationDate;
		
		private string _Environment;
		
		private string _Who;
		
		private System.Nullable<short> _RateOfUnease;
		
		private string _Notes;
		
		public prc_RetrieveConversationsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConversationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ConversationDate
		{
			get
			{
				return this._ConversationDate;
			}
			set
			{
				if ((this._ConversationDate != value))
				{
					this._ConversationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Environment", DbType="NVarChar(100)")]
		public string Environment
		{
			get
			{
				return this._Environment;
			}
			set
			{
				if ((this._Environment != value))
				{
					this._Environment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Who", DbType="NVarChar(100)")]
		public string Who
		{
			get
			{
				return this._Who;
			}
			set
			{
				if ((this._Who != value))
				{
					this._Who = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RateOfUnease", DbType="SmallInt")]
		public System.Nullable<short> RateOfUnease
		{
			get
			{
				return this._RateOfUnease;
			}
			set
			{
				if ((this._RateOfUnease != value))
				{
					this._RateOfUnease = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(1000)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
	}
	
	public partial class prc_InsertConversationResult
	{
		
		private System.Nullable<decimal> _Id;
		
		public prc_InsertConversationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
